language: python
sudo: false
python:
  - "3.5"
# command to install dependencies
install:
  - travis_retry pip install -r DEPENDENCIES
# command to run tests
script:
  - pep8 dnssec_zonetools tests
  - pylint dnssec_zonetools tests
  - nose2 -v
